"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var authors_1 = require("./authors");
var book_1 = require("./book");
var library_1 = require("./library");
var member_1 = require("./member");
var library = new library_1.Library();
var author1 = new authors_1.Author(1, "abc");
var author2 = new authors_1.Author(2, "xyz");
library.addAuthor(author1);
library.addAuthor(author2);
var book1 = new book_1.Book(1, "aaaa", author1.id, 5);
var book2 = new book_1.Book(2, "bbbb", author1.id, 3);
var book3 = new book_1.Book(3, "cccc", author2.id, 1);
library.addBook(book1);
library.addBook(book2);
library.addBook(book3);
var member1 = new member_1.Member(1, "mno", "mno@example.com");
var member2 = new member_1.Member(2, "ijk", "ijk@example.com");
library.addMember(member1);
library.addMember(member2);
member1.borrowBook(book1);
member2.borrowBook(book1);
member1.returnBook(book1);
member2.borrowBook(book3);
member1.returnBook(book3);
member1.borrowBook(book3);
